import pytest
from alembic.config import Config
from alembic import command
from database import engine, Base

@pytest.mark.asyncio
async def test_no_uncommitted_migration_drift():
    """
    Fails if SQLAlchemy models have pending changes not recorded in Alembic migrations.
    """
    alembic_cfg = Config("alembic.ini")

    # 1. Wipe raw tables generated by conftest fixtures so Alembic starts clean
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)

    try:
        # 2. Run Alembic migrations from base to head
        command.upgrade(alembic_cfg, "head")
        
        # 3. Verify zero drift between SQLAlchemy Base metadata and Alembic migrations
        command.check(alembic_cfg)
    except Exception as e:
        pytest.fail(f"Alembic migration drift detected! Run 'alembic revision --autogenerate': {e}")
    finally:
        # 4. Clean up schema for subsequent tests
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.drop_all)
